### ISSUE TITLE
Extend Service Builder

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada-operator#105]
Currently we have a very simple builder for services: 

https://github.com/armadaproject/armada-operator/blob/main/controllers/builders/service.go

The issue with this is that many armada components need more complicated service support, for example armada-server.
https://github.com/armadaproject/armada/blob/master/deployment/armada/templates/service.yaml

We should extend the builder to cover all the common service attributes between armada components, and then allow "injection" functions to add the differences.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/AR-145) by [Unito](https://www.unito.io)

**Comment by richscott** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada-operator/105?planning-poker) with Zenhub @ClifHouck @dejanzele @kannon92 @richscott @Sharpz7 @suprjinx
