### ISSUE TITLE
General way to construct a pod template in a deployment spec

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada-operator#11]
Our operators should start the deployments.  Every operator should generate a deployment that mounts the application config.  Hopefully, we can build a generate function for this that can be reused for the other deployments

**Comment by richscott** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada-operator/11?planning-poker) with Zenhub @richscott @kannon92 @Sharpz7

**Comment by richscott** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada-operator/11?planning-poker) with Zenhub @dejanzele
