### ISSUE TITLE
Move Copyright to 2023

### ISSUE THREAD

**Issue by Sharpz7** [armadaproject/armada-operator#17]
"We live in the future now"

- @ClifHouck 
![](https://files.mcaq.me/x3131.jpg)

**Comment by kannon92** [comment]
https://softwareengineering.stackexchange.com/questions/130478/what-copyright-date-for-an-update-to-an-open-source-project-from-last-year

Reading this over and seeing the code in Kubernetes I think technically it is correct that we have it as 2022.  

You don't need this to be the current year but the year from when you started development.  

See job controller in Kubernetes for an example: 

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/indexed_job_utils.go

I think we can leave this as is tbh.
