### ISSUE TITLE
Add Integration Tests for Webhooks

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada-operator#25]
We have 0 test coverage around our webhook implementation.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/AR-156) by [Unito](https://www.unito.io)

**Comment by richscott** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada-operator/25?planning-poker) with Zenhub @kannon92 @richscott @Sharpz7

**Comment by ClifHouck** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada-operator/25?planning-poker) with Zenhub @ClifHouck

**Comment by richscott** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Armada-62c744dc3b819100132ca032/issues/armadaproject/armada-operator/25?planning-poker) with Zenhub @dejanzele
