### ISSUE TITLE
Back-off pulling image "gcr.io/kubebuilder/kube-rbac-proxy:0.13.0"

### ISSUE THREAD

**Issue by csantanapr** [armadaproject/armada-operator#300]
Installing helm operator gives error
```
Back-off pulling image "gcr.io/kubebuilder/kube-rbac-proxy:0.13.0"
```
The image `gcr.io/kubebuilder/kube-rbac-proxy:0.13.0` doesn't exist. the version is `v0.13.0` not `0.13.0`

The deployment should not have the sidecard container for webhook rbac-proxy, this only need it when your doing development using kubebuilder for example. The sidecard should be remove from the helm chart, this is handled by using cert manager when your CRDs and Operator is deployed.

**Comment by dejanzele** [comment]
This is fixed in latest releases
