### ISSUE TITLE
Cancellation issue + armadactl issue

### ISSUE THREAD

**Issue by wilson-duan** [armadaproject/armada-operator#308]
I installed armada with the make kind-all command. When I submit a job and try to cancel it through Lookout, it gives me an error: All jobs failed to cancel. See table for error responses. I would like to note that using armadactl to cancel jobs works just fine, it is only through Lookout that the errors show up.

Furthermore, when I use the armadactl for specific use cases such as `armadactl get scheduling-report `and `armadactl get job-report <job-id>`, I get the error: Error: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = “transport: Error while dialing: dial tcp [::1]:50052: connect: connection refused".

**Comment by dejanzele** [comment]
Hi @wilson-duan,

Can you check in the `armada` namespace are all components up & running?

**Comment by wilson-duan** [comment]
@dejanzele Yes, all armada components and all armada dependencies are up and running.

**Comment by dejanzele** [comment]
Fixed in v0.3.0
