### ISSUE TITLE
TypeError: Failed to fetch in lookout UI while cancelling jobs or check job logs

### ISSUE THREAD

**Issue by PhilC1234** [armadaproject/armada-operator#311]
When I tried to cancel the selected jobs, or check the log for a job, it failed with "TypeError: Failed to fetch".

![Screenshot 2024-07-17 at 1 19 31 PM](https://github.com/user-attachments/assets/6b99a67e-1893-40f2-ae33-1888a5b145bc)

**Comment by dejanzele** [comment]
This is fixed in the latest v0.3.0 release
