### ISSUE TITLE
Controller should include readiness/liveness checks in deployments 

### ISSUE THREAD

**Issue by Sovietaced** [armadaproject/armada-operator#334]
I don't believe the controller includes readiness/lives checks on any of the deployments which seems important. We are having a production issue where lookout stops accepting TCP connections and this would likely have been discovered by a liveness check. 

I should have a pull request up in the next week to add support for this.

**Comment by dejanzele** [comment]
Yes, definitely, we need liveness/readiness checks.

Not all Armada components exposed healthcheck routes before, but a lot of things have progressed.

The Helm charts (https://github.com/armadaproject/armada/tree/master/deployment) should accuratelly reflect what is supported, and the Operator should follow changes to the Helm charts.
