### ISSUE TITLE
Use whatever G-Research uses to install prometheus in their clusters for our dev cluster

### ISSUE THREAD

**Issue by ClifHouck** [armadaproject/armada-operator#89]
@kannon92 has more context here, but the main point is contained within the title.

**Comment by kannon92** [comment]
https://github.com/prometheus-operator/prometheus-operator

**Comment by kannon92** [comment]
We actually use these APIS in our operator so I think we actually need to migrate Prometheus to the operator

`	monitoringv1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"`

**Comment by ClifHouck** [comment]
> 

I'm not sure I quite follow you here. What do you mean `need to migrate Prometheus to the operator`?

**Comment by kannon92** [comment]
We need to use the prometheus operator as we use their APIs for setting up prometheus.  

So we should remove the bitnami chart for Prometheus and install https://github.com/prometheus-operator/prometheus-operator
