### ISSUE TITLE
Ports should be retrieved from the application config for our components

### ISSUE THREAD

**Issue by kannon92** [armadaproject/armada-operator#96]
Currently we are hardcoding ports but we should read these ports from applicationConfig.  

We should also maybe consider putting validation logic in applicationConfig as we can't really start some of our components without knowing what ports to start.  

https://github.com/armadaproject/armada-operator/blob/main/controllers/install/executor_controller.go#L337 for an example.  

Basically everywhere where we set ports we should be reading these from the config files rather than assuming they will always be set to particular values.

**Comment by Mo-Fatah** [comment]
Is this issue still valid ? I looked into the code and didn't find hardcoded ports other than test files. I think it was solved here #113

**Comment by kannon92** [comment]
Thanks for catching that.
